# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-06 08:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classtering1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=900)),
                ('is_foori', models.BooleanField(default=False)),
                ('has_pic', models.BooleanField(default=False)),
                ('city', models.CharField(default='Tehran', max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('picture_loc', models.CharField(default='no_pic.png', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Classtering2',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='divar.Classtering1')),
            ],
        ),
        migrations.AddField(
            model_name='stuff',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divar.UserProfile'),
        ),
        migrations.CreateModel(
            name='Classtering3',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='divar.Classtering2')),
            ],
        ),
        migrations.AddField(
            model_name='stuff',
            name='classtering3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='divar.Classtering3'),
        ),
    ]
