# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-29 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classtering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divar.Classtering')),
            ],
        ),
        migrations.RemoveField(
            model_name='classtering2',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='classtering3',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='stuff',
            name='classtering3',
        ),
        migrations.AlterField(
            model_name='stuff',
            name='picture_loc',
            field=models.ImageField(blank=True, null=True, upload_to='stuff_images'),
        ),
        migrations.DeleteModel(
            name='Classtering1',
        ),
        migrations.DeleteModel(
            name='Classtering2',
        ),
        migrations.DeleteModel(
            name='Classtering3',
        ),
        migrations.AddField(
            model_name='stuff',
            name='classtering',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='divar.Classtering'),
        ),
    ]
