# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-26 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classtering1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=900)),
                ('is_foori', models.BooleanField()),
                ('has_pic', models.BooleanField()),
                ('city', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divar.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Classtering2',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='divar.Classtering1')),
            ],
        ),
        migrations.CreateModel(
            name='Classtering3',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='divar.Classtering2')),
            ],
        ),
        migrations.AddField(
            model_name='stuff',
            name='classtering3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divar.Classtering3'),
        ),
    ]
