# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-27 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuff',
            name='picture_loc',
        ),
    ]
