# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-29 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divar', '0003_stuff_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='stuff',
            name='picture',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='pictures/%Y/%m/%D/'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divar.Stuff'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divar.UserProfile'),
        ),
    ]
